### ISSUE TITLE
可用其它字符代替 `sed` 中的 `s///`

### ISSUE THREAD

**Issue by heroxbd** [ukui/ukui-overlay#6]
https://github.com/ukui/ukui-overlay/blob/e32553c4e9925185d20b4bf936662ce0332339ca/ukui-base/ukui-interface/ukui-interface-1.0.1-r3.ebuild#L29

如， `s,iniparser/iniparser,iniparser4/iniparser,g`

**Comment by OriPoin** [comment]
fixed: 
- [ukui-base/ukui-interface](https://github.com/ukui/ukui-overlay/commit/37589b7073230a94f1346f8d3e57465e2f3da636)
- [ukui-base/ukui-media](https://github.com/ukui/ukui-overlay/commit/ba4e9e3d29a5c6fca00be93364b095415dc58c3e)
- [ukui-base/ukui-power-manager](https://github.com/ukui/ukui-overlay/commit/676a940602632d0a0837b2bc93e0c0aef896fce1)
