### ISSUE TITLE
外部命令需要 `|| die`

### ISSUE THREAD

**Issue by heroxbd** [ukui/ukui-overlay#7]
https://github.com/ukui/ukui-overlay/blob/e32553c4e9925185d20b4bf936662ce0332339ca/ukui-base/ukui-interface/ukui-interface-1.0.1-r3.ebuild#L53

`sed` , `mkdir`, `mv` 等外部命令都需要加上 `|| die` ，保证出错时 `ebuild` 能及时挂掉。

**Comment by OriPoin** [comment]
fixed: 
- [ukui-base/ukui-interface](https://github.com/ukui/ukui-overlay/commit/37589b7073230a94f1346f8d3e57465e2f3da636)
- [gnome-base/libgnome-keyring](https://github.com/ukui/ukui-overlay/commit/75293cfdafa9621046dc419ee876534feb57262f)
- [ukui-base/ukui-media](https://github.com/ukui/ukui-overlay/commit/ba4e9e3d29a5c6fca00be93364b095415dc58c3e)
- [ukui-base/ukui-power-manager](https://github.com/ukui/ukui-overlay/commit/676a940602632d0a0837b2bc93e0c0aef896fce1)
- [x11-wm/ukui-kwin](https://github.com/ukui/ukui-overlay/commit/4e9f43e8d1e27da5dbfa310abb9f5cf0a54d6ada)

**Comment by heroxbd** [comment]
多谢！完成后，你可以直接关闭 issue 。
