### ISSUE TITLE
libgnome-keyring

### ISSUE THREAD

**Issue by wat9rz** [ukui/ukui-overlay#8]
>>> Emerging (24 of 65) gnome-base/libgnome-keyring-3.12.0-r1::ukui
 * libgnome-keyring-3.12.0.tar.xz BLAKE2B size ;-) ...                                                                                                                         [ ok ]
>>> Unpacking source...
>>> Unpacking libgnome-keyring-3.12.0.tar.xz to /var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/work
>>> Source unpacked in /var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/work
>>> Preparing source in /var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/work/libgnome-keyring-3.12.0 ...
/var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/temp/environment: line 496: ./autogen.sh: No such file or directory
 * ERROR: gnome-base/libgnome-keyring-3.12.0-r1::ukui failed (prepare phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 122:  Called src_prepare
 *   environment, line 496:  Called die
 * The specific snippet of code:
 *       NOCONFIGURE=1 ./autogen.sh || die
 * 
 * If you need support, post the output of `emerge --info '=gnome-base/libgnome-keyring-3.12.0-r1::ukui'`,
 * the complete build log and the output of `emerge -pqv '=gnome-base/libgnome-keyring-3.12.0-r1::ukui'`.
 * The complete build log is located at '/var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/work/libgnome-keyring-3.12.0'
 * S: '/var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/work/libgnome-keyring-3.12.0'

>>> Failed to emerge gnome-base/libgnome-keyring-3.12.0-r1, Log file:

>>>  '/var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/temp/build.log'

 * Messages for package kde-frameworks/solid-5.97.0:

 * Install additional packages for optional runtime features:
 *   app-misc/media-player-info for media player devices support

 * Messages for package gnome-base/libgnome-keyring-3.12.0-r1:

 * ERROR: gnome-base/libgnome-keyring-3.12.0-r1::ukui failed (prepare phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 122:  Called src_prepare
 *   environment, line 496:  Called die
 * The specific snippet of code:
 *       NOCONFIGURE=1 ./autogen.sh || die
 * 
 * If you need support, post the output of `emerge --info '=gnome-base/libgnome-keyring-3.12.0-r1::ukui'`,
 * the complete build log and the output of `emerge -pqv '=gnome-base/libgnome-keyring-3.12.0-r1::ukui'`.
 * The complete build log is located at '/var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/work/libgnome-keyring-3.12.0'
 * S: '/var/tmp/portage/gnome-base/libgnome-keyring-3.12.0-r1/work/libgnome-keyring-3.12.0'

**Comment by OriPoin** [comment]
gnome-base/libgnome-keyring is old depend from dpkg packing. I will remove it.

**Comment by wat9rz** [comment]
youre amazing
